# Supplementary config file to achieve higher downlinke rates by enabling higher order modulation scheme and reduce SSB transmission periodicity.

cell_cfg:
  pdsch:
    mcs_table: qam256  # Use QAM256 MCS table in downlink
  ssb:
    ssb_period: 20     # Increase SSB periodicity to 20ms